import React from 'react';
import { NeonButton } from './NeonButton';
import { cn } from './ui/utils';
import { Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface Flashcard {
  front: string;
  back: string;
}

interface DeckData {
  title: string;
  description: string;
  cards: Flashcard[];
}

interface DeckImportExportProps {
  onExport: () => DeckData;
  className?: string;
  title?: string;
}

export const DeckImportExport: React.FC<DeckImportExportProps> = ({
  onExport,
  className,
  title = "Deck Data"
}) => {
  const handleExportPDF = () => {
    const data = onExport();
    const doc = new jsPDF();
    
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const contentWidth = pageWidth - (margin * 2);
    
    // Header Section
    doc.setFillColor(240, 240, 250);
    doc.rect(0, 0, pageWidth, 45, 'F');
    
    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(40, 40, 100);
    doc.text(data.title.toUpperCase(), margin, 25);
    
    // Description
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 120);
    doc.text(data.description || "No description provided.", margin, 35, { maxWidth: contentWidth });
    
    // Divider
    doc.setDrawColor(100, 100, 150);
    doc.setLineWidth(0.5);
    doc.line(margin, 40, pageWidth - margin, 40);
    
    let y = 55;
    
    // Cards
    data.cards.forEach((card, i) => {
      const lineHeight = 7;
      const frontLines = doc.splitTextToSize(card.front, contentWidth - 15);
      const backLines = doc.splitTextToSize(card.back, contentWidth - 15);
      
      // Dynamic height calculation with extra padding for labels and margins
      const cardHeight = (frontLines.length * lineHeight) + (backLines.length * lineHeight) + 35;
      
      // Page break check
      if (y + cardHeight > 275) {
        doc.addPage();
        y = 20;
      }
      
      // Card Container - Solid border with consistent padding
      doc.setDrawColor(200, 200, 220); // Slightly darker border
      doc.setLineWidth(0.2);
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(margin - 4, y - 8, contentWidth + 8, cardHeight, 3, 3, 'FD');
      
      const textPadding = margin + 2;
      
      // Card Number Label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(140, 140, 160);
      doc.text(`FLASHCARD #${i + 1}`, textPadding, y);
      y += 8;
      
      // Front Section
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(70, 70, 90);
      doc.text("FRONT:", textPadding, y);
      y += 6;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 50);
      doc.text(frontLines, textPadding + 2, y, { lineHeightFactor: 1.2 });
      y += (frontLines.length * lineHeight) + 6;
      
      // Back Section
      doc.setFont("helvetica", "bold");
      doc.setTextColor(70, 70, 90);
      doc.text("BACK:", textPadding, y);
      y += 6;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 50);
      doc.text(backLines, textPadding + 2, y, { lineHeightFactor: 1.2 });
      y += (backLines.length * lineHeight) + 15; // Space between cards
    });
    
    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(180);
        doc.text(`Generated by FlashLearn AI - Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: 'center' });
    }
    
    const safeTitle = data.title.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const fileName = `flashlearn-${safeTitle || 'deck'}.pdf`;
    doc.save(fileName);
  };

  return (
    <div className={cn('flex flex-wrap items-center gap-3', className)}>
      <div className="text-xs text-muted-foreground font-['Press_Start_2P'] uppercase mr-2 hidden sm:block">
        {title}:
      </div>
      <NeonButton
        variant="secondary"
        onClick={handleExportPDF}
        className="flex items-center gap-2"
        size="sm"
      >
        <Download className="w-3 h-3" />
        Export to PDF
      </NeonButton>
    </div>
  );
};
